server:
  port: 7777

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/service-patient/**
          filters:
            - RewritePath=/service-patient/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: FallBack-Patient
                fallbackuri: forward:/defaultPatients
          uri: lb://ms-patient

        - id: route2
          predicates:
            - Path=/service-ordonnance/**
          filters:
            - RewritePath=/service-ordonnance/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: FallBack-Patient
                fallbackuri: forward:/defaultOrdonnances
          uri: lb://ms-ordonnance
